### ISSUE TITLE
Metrics events tracking items

### ISSUE THREAD

**Issue by robobenklein** [utk-se/CodeRibbon#62]
The following events I think should be part of a metrics reporter:

 - [ ] Opens item in patch:
   - [ ] Which visual location on screen
   - [ ] Which location in whole ribbon
   - [ ] Which initiator of open (in-patch, drag, or out-of-patch)
 - [ ] Total length of ribbon
 - [ ] Fill percentage of ribbon
   - [ ] Extra: Bias between rows? (prefer top, etc?)
 - [ ] Drags item between patches
   - [ ] Which event handler? (html5 vs atom swap)
   - [ ] If drag was to offscreen patch from start of drag
 - [ ] Closes patch
 - [ ] Uses overview mode
 - [ ] Uses a single patch column

**Comment by robobenklein** [comment]
Also catch-all errors...

**Comment by AZHenley** [comment]
If the event logging is set up correctly, we would be able to simulate the programmers' coderibbon environment, such as how long patches stay open, how they arrange them, the length of the ribbon, etc.

Events for opening, closing, and moving patches.
Event for editing code in a patch (don't need fine grain edits).
Events for copy and pasting from one patch to another. 
Event for the active patch changing (e.g., the active editor changes when they click into a different patch)
Event for scrolling the ribbon left/right (we'd like to know when the visible patches changes and what they are).
